# -*- coding: utf-8 -*-
"""OCR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ppa81UTpGC0GyT1bM0GzsCMkAjBhQhn_
"""

# !sudo apt install tesseract-ocr
# !pip install pytesseract
from PIL import Image

import pytesseract
import requests
import shutil


def img_to_str(image_url):
    # image_url = "https://cdn.pixabay.com/photo/2020/02/06/09/39/summer-4823612_960_720.jpg"
    filename = image_url.split("/")[-1]

    
    r = requests.get(image_url, stream = True)

  
    if r.status_code == 200:
        
        r.raw.decode_content = True
        with open(filename,'wb') as f:
          shutil.copyfileobj(r.raw, f)
        # print('Image sucessfully Downloaded: ',filename)
        print(pytesseract.image_to_string(filename))

    else:
        print('Image Couldn\'t be retreived')